# 1.3. Introducing the multidimensional array in NumPy for fast array computations

In [2]:
import random
import numpy as np

In [6]:
n = 10
x = [random.random() for _ in range(n)]
y = [random.random() for _ in range(n)]

In [24]:
x, y

([0.9475017741392506,
  0.44470735285883434,
  0.06959397591561312,
  0.7105835836936985,
  0.5157511868280061,
  0.20489795485122753,
  0.5236509354174506,
  0.2837416737106143,
  0.4407017944761309,
  0.03896347168546366],
 [0.5963203699052396,
  0.7035707632679694,
  0.5108380296313554,
  0.7526075658108224,
  0.2641934517045781,
  0.15005222181735667,
  0.8048640483511873,
  0.25585171403082463,
  0.018632299183215628,
  0.27010853480725283])

In [7]:
z = [x[i] + y[i] for i in range(n)]
z

[1.5438221440444901,
 1.1482781161268036,
 0.5804320055469685,
 1.463191149504521,
 0.7799446385325842,
 0.3549501766685842,
 1.3285149837686379,
 0.539593387741439,
 0.4593340936593465,
 0.3090720064927165]

In [9]:
%timeit [x[i] + y[i] for i in range(n)]

1.41 µs ± 13.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [18]:
xa = np.array(x)
ya = np.array(y)

10

In [20]:
xa

array([0.94750177, 0.44470735, 0.06959398, 0.71058358, 0.51575119,
       0.20489795, 0.52365094, 0.28374167, 0.44070179, 0.03896347])

In [21]:
za = xa + ya
za

array([1.54382214, 1.14827812, 0.58043201, 1.46319115, 0.77994464,
       0.35495018, 1.32851498, 0.53959339, 0.45933409, 0.30907201])

In [22]:
%timeit xa + ya

516 ns ± 4.72 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [25]:
%timeit sum(x)  # pure Python

162 ns ± 4.38 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [27]:
%timeit np.sum(xa)  # NumPy, so much faster

3.82 µs ± 61.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [29]:
d = [abs(x[i] - y[j])
     for i in range(10)
     for j in range(10)]

In [30]:
d

[0.351181404234011,
 0.24393101087128122,
 0.43666374450789525,
 0.1948942083284282,
 0.6833083224346725,
 0.797449552321894,
 0.14263772578806333,
 0.691650060108426,
 0.928869474956035,
 0.6773932393319978,
 0.15161301704640529,
 0.2588634104091351,
 0.06613067677252105,
 0.3079002129519881,
 0.18051390115425625,
 0.29465513104147767,
 0.36015669549235296,
 0.1888556388280097,
 0.4260750536756187,
 0.1745988180515815,
 0.5267263939896265,
 0.6339767873523563,
 0.44124405371574227,
 0.6830135898952093,
 0.19459947578896497,
 0.08045824590174355,
 0.7352700724355742,
 0.1862577381152115,
 0.05096167673239749,
 0.20051455889163972,
 0.11426321378845883,
 0.007012820425729038,
 0.19974555406234307,
 0.04202398211712399,
 0.44639013198912036,
 0.5605313618763418,
 0.09428046465748885,
 0.4547318696628738,
 0.6919512845104828,
 0.4404750488864456,
 0.08056918307723349,
 0.18781957643996328,
 0.004913157196650753,
 0.2368563789828163,
 0.25155773512342805,
 0.36569896501064947,
 0.289112861

In [32]:
da = np.abs(xa[:10, np.newaxis] - ya[:10])

In [33]:
da

array([[0.3511814 , 0.24393101, 0.43666374, 0.19489421, 0.68330832,
        0.79744955, 0.14263773, 0.69165006, 0.92886947, 0.67739324],
       [0.15161302, 0.25886341, 0.06613068, 0.30790021, 0.1805139 ,
        0.29465513, 0.3601567 , 0.18885564, 0.42607505, 0.17459882],
       [0.52672639, 0.63397679, 0.44124405, 0.68301359, 0.19459948,
        0.08045825, 0.73527007, 0.18625774, 0.05096168, 0.20051456],
       [0.11426321, 0.00701282, 0.19974555, 0.04202398, 0.44639013,
        0.56053136, 0.09428046, 0.45473187, 0.69195128, 0.44047505],
       [0.08056918, 0.18781958, 0.00491316, 0.23685638, 0.25155774,
        0.36569897, 0.28911286, 0.25989947, 0.49711889, 0.24564265],
       [0.39142242, 0.49867281, 0.30594007, 0.54770961, 0.0592955 ,
        0.05484573, 0.59996609, 0.05095376, 0.18626566, 0.06521058],
       [0.07266943, 0.17991983, 0.01281291, 0.22895663, 0.25945748,
        0.37359871, 0.28121311, 0.26779922, 0.50501864, 0.2535424 ],
       [0.3125787 , 0.41982909, 0.2270963

In [34]:
%timeit [abs(x[i] - y[j]) \
         for i in range(10) \
         for j in range(10)]

16.2 µs ± 500 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [36]:
%timeit np.abs(xa[:,np.newaxis] - ya)

2.9 µs ± 75.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
