# 4.2. Profiling your code easily with cProfile and IPython

In [1]:
import numpy as np

In [6]:
%prun?

Docstring:
Run a statement through the python code profiler.

Usage, in line mode:
  %prun [options] statement

Usage, in cell mode:
  %%prun [options] [statement]
  code...
  code...

In cell mode, the additional code lines are appended to the (possibly
empty) statement in the first line.  Cell mode allows you to easily
profile multiline blocks without having to put them in a separate
function.

The given statement (which doesn't require quote marks) is run via the
python profiler in a manner similar to the profile.run() function.
Namespaces are internally managed to work correctly; profile.run
cannot be used in IPython because it makes certain assumptions about
namespaces which do not hold under IPython.

Options:

-l <limit>
  you can place restrictions on what or how much of the
  profile gets printed. The limit value can be:

     * A string: only information for function names containing this string
       is printed.

     * An integer: only these many lines are printed.

     *

In [2]:
def step(*shape):
    # Create a random n-vector with +1 or -1 values.
    return 2 * (np.random.random_sample(shape)<.5) - 1

In [5]:
%%prun -s cumulative -q -l 10 -T prun0
# We profile the cell, sort the report by "cumulative
# time", limit it to 10 lines, and save it to a file
# named "prun0".

n = 10000
iterations = 50
x = np.cumsum(step(iterations, n), axis=0)
bins = np.arange(-30, 30, 1)
y = np.vstack([np.histogram(x[i,:], bins)[0]
               for i in range(iterations)])

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 1 0 0]]
 
*** Profile printout saved to text file 'prun0'. 


In [4]:
print(open('prun0', 'r').read())

         2829 function calls (2527 primitive calls) in 0.047 seconds

   Ordered by: cumulative time
   List reduced from 58 to 10 due to restriction <10>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.047    0.047 {built-in method builtins.exec}
        1    0.000    0.000    0.047    0.047 <string>:5(<module>)
   354/52    0.002    0.000    0.033    0.001 {built-in method numpy.core._multiarray_umath.implement_array_function}
        1    0.000    0.000    0.027    0.027 <string>:9(<listcomp>)
       50    0.000    0.000    0.027    0.001 <__array_function__ internals>:2(histogram)
       50    0.002    0.000    0.027    0.001 histograms.py:670(histogram)
       50    0.000    0.000    0.018    0.000 <__array_function__ internals>:2(sort)
       50    0.000    0.000    0.018    0.000 fromnumeric.py:826(sort)
       50    0.017    0.000    0.017    0.000 {method 'sort' of 'numpy.ndarray' objects}
        1    0.002    0.002   

```bash
$ python -m cProfile -o profresults myscript.py
```

```
import pstats
p = pstats.Stats('profresults')
p.strip_dirs().sort_stats("cumulative").print_stats()
```